### ISSUE TITLE
doesn't work :(

### ISSUE THREAD

**Issue by xem** [tomhodgins/varius#1]
:p j/k can't wait to see that

**Comment by tomhodgins** [comment]
Hmmm, can you tell me in which browsers this didn't work for you? Maybe you can submit a Pull Request with any bugfixes :D

**Comment by xem** [comment]
I tried in node after executing "yarn rollup glslify", and my ES8linter complained that there was no JS file...

**Comment by tomhodgins** [comment]
Oh you're still on ES8? :S I'm not sure if you can use it with your workflow

**Comment by tomhodgins** [comment]
Ooops, I pushed the code :/
